### PR TITLE
Fix canvas file name, replace white spaces , /, :, (, ).

### PR DESCRIPTION
**Pull request by davizucon**
This patch fixes the invalid path when generate file name from canvas name.

### CODE REVIEW

**Comment by fikovnik** [comment]
Thanks for contributing!

I agree that '/' should be handled - removed from the name, but the other characters are all valid in file names. I don't think they should be handled in any special way.

**Comment by davizucon** [comment]
Yeah, I think '/' and ':' cannot be used, I`ll make another PR.

**Comment by davizucon** [comment]
Updated :)

**Comment by fikovnik** [comment]
':' is actually valid.

**Comment by davizucon** [comment]
Maybe depends .... 

screen shot 2016-09-06 at 17 23 58

**Comment by fikovnik** [comment]
I tried:

```
$ touch "a:b"
$ ls -l
-rw-r--r--    1 krikava  staff     0 Sep  6 16:25 a:b
```

**Comment by davizucon** [comment]
yeah, I think there is a inconsistency between Finder and filesystem in (OS X). If you look the file created in Finder, you'll see there is no ":", instead , it's presents a/b, I tried to rename, it works if I no type ":". 

I dnt know... can create file like "a:b" and see in finder with "a/b" (no problem at all) or avoid "visual" mistake removing ":" (no problem too) up to you.

I'm already glad for this project, saved my day :)

Thanks!!!

**Comment by fikovnik** [comment]
Let's remove (replace with "") both ':' and '/' then. Just to be sure.

Thanks!

**Comment by davizucon** [comment]
@fikovnik  Sure !
Done.

Thanks!!!

**Pull request merged**
